### ISSUE TITLE
How about the code

### ISSUE THREAD

**Issue by taiguduizhang** [xrenaa/Safety-Aware-Motion-Prediction#2]
Hi! I've red this paper, and how can I get the code ?

**Comment by xrenaa** [comment]
Hi, I am preparing the code for serveral papers. I hope that I can release the code very fast. 

If you need the processed data, I may share with you.

**Comment by taiguduizhang** [comment]
I'd be very appreciated if you send the processed data to this email! Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xuanchi ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 下午4:06
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xrenaa/Safety-Aware-Motion-Prediction] How about the code (Issue #2)





 
Hi, I am preparing the code for serveral papers. I hope that I can release the code very fast.
 
If you need the processed data, I may share with you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xrenaa** [comment]
The data at: https://drive.google.com/file/d/1VyUFza_gGaqNiPQxLX_JOUi3gpplmrbs/view?usp=sharing

The dataloader is at:

```
import torch
import torch.nn as nn
import torchvision.transforms as tfs

class Dataset(torch.utils.data.Dataset):
    def __init__(self, data_dir):
        super(Dataset, self).__init__()
        
        self.data = np.load(data_dir)
        
        self.input = self.data["input"]
        self.target = self.data["target"]
        self.atten = self.data["attention"]

        self.size = self.input.shape[0]

    def __getitem__(self, index):
        
        input_img = self.input[index]
        input_img = tfs.functional.to_tensor(input_img)
        target_img = self.target[index]
        mask_img = tfs.functional.to_tensor(self.atten[index])
        
        return input_img, target_img, mask_img

    def __len__(self):
        return self.size
```

**Comment by taiguduizhang** [comment]
Thx！



发自我的iPhone


------------------ Original ------------------
From: Xuanchi Ren ***@***.***&gt;
Date: Mon,Feb 28,2022 10:16 PM
To: xrenaa/Safety-Aware-Motion-Prediction ***@***.***&gt;
Cc: taiguduizhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [xrenaa/Safety-Aware-Motion-Prediction] How about the code (Issue #2)





 
The data at: https://drive.google.com/file/d/1VyUFza_gGaqNiPQxLX_JOUi3gpplmrbs/view?usp=sharing
 
The dataloader is at:
 import torch import torch.nn as nn import torchvision.transforms as tfs class Dataset(torch.utils.data.Dataset):     def __init__(self, data_dir):         super(Dataset, self).__init__()                  self.data = np.load(data_dir)                  self.input = self.data["input"]         self.target = self.data["target"]         self.atten = self.data["attention"]         self.size = self.input.shape[0]     def __getitem__(self, index):                  input_img = self.input[index]         input_img = tfs.functional.to_tensor(input_img)         target_img = self.target[index]         mask_img = tfs.functional.to_tensor(self.atten[index])                  return input_img, target_img, mask_img     def __len__(self):         return self.size  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
